------------------------------------------------------------
-- PROJETO: CLYVO VET - SAUDE PREDITIVA PET
-- DISCIPLINA: MASTERING RELATIONAL AND NON-RELATIONAL DATABASE
-- ARQUIVO: 01_DDL.sql
-- DESCRICAO: CRIACAO DE TODAS AS TABELAS EM 3FN
-- EXECUCAO: 1º - executar antes de qualquer outro arquivo
------------------------------------------------------------

------------------------------------------------------------
-- TABELA: ESTADO
------------------------------------------------------------
CREATE TABLE T_CLY_ESTADO (
    COD_ESTADO        CHAR(2)        NOT NULL,
    NOME_ESTADO       VARCHAR2(50)   NOT NULL,

    CONSTRAINT PK_CLY_ESTADO
        PRIMARY KEY (COD_ESTADO)
);

------------------------------------------------------------
-- TABELA: CIDADE
------------------------------------------------------------
CREATE TABLE T_CLY_CIDADE (
    COD_CIDADE        NUMBER(10)      NOT NULL,
    COD_ESTADO        CHAR(2)         NOT NULL,
    NOME_CIDADE       VARCHAR2(100)   NOT NULL,

    CONSTRAINT PK_CLY_CIDADE
        PRIMARY KEY (COD_CIDADE),

    CONSTRAINT FK_CLY_CIDADE_ESTADO
        FOREIGN KEY (COD_ESTADO)
        REFERENCES T_CLY_ESTADO(COD_ESTADO)
);

------------------------------------------------------------
-- TABELA: TIPO_ENDERECO
------------------------------------------------------------
CREATE TABLE T_CLY_TIPO_ENDERECO (
    COD_TIPO_ENDERECO     NUMBER(2)      NOT NULL,
    DES_TIPO_ENDERECO     VARCHAR2(50)   NOT NULL,

    CONSTRAINT PK_CLY_TIPO_ENDERECO
        PRIMARY KEY (COD_TIPO_ENDERECO)
);

------------------------------------------------------------
-- TABELA: USUARIO
------------------------------------------------------------
CREATE TABLE T_CLY_USUARIO (
    ID_USUARIO        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME              VARCHAR2(150)    NOT NULL,
    CPF               VARCHAR2(14)     NOT NULL,
    EMAIL             VARCHAR2(150)    NOT NULL,
    SENHA             VARCHAR2(255)    NOT NULL,
    DT_CADASTRO       DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_CLY_USUARIO
        PRIMARY KEY (ID_USUARIO),

    CONSTRAINT UK_CLY_USUARIO_CPF
        UNIQUE (CPF),

    CONSTRAINT UK_CLY_USUARIO_EMAIL
        UNIQUE (EMAIL)
);

------------------------------------------------------------
-- TABELA: ENDERECO_USUARIO
------------------------------------------------------------
CREATE TABLE T_CLY_ENDERECO_USUARIO (
    SEQ_ENDERECO_USUARIO    NUMBER(10)      NOT NULL,
    ID_USUARIO              NUMBER          NOT NULL,
    COD_TIPO_ENDERECO       NUMBER(2)       NOT NULL,
    COD_CIDADE              NUMBER(10)      NOT NULL,
    DES_ENDERECO            VARCHAR2(150)   NOT NULL,
    NUM_ENDERECO            VARCHAR2(20),
    DES_COMPLEMENTO         VARCHAR2(100),
    NUM_CEP                 VARCHAR2(9),
    DES_BAIRRO              VARCHAR2(100),
    STA_ATIVO               CHAR(1) DEFAULT 'S',
    DAT_CADASTRO            DATE DEFAULT SYSDATE,

    CONSTRAINT PK_CLY_END_USUARIO
        PRIMARY KEY (SEQ_ENDERECO_USUARIO),

    CONSTRAINT FK_CLY_END_USUARIO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES T_CLY_USUARIO(ID_USUARIO),

    CONSTRAINT FK_CLY_END_USUARIO_TIPO
        FOREIGN KEY (COD_TIPO_ENDERECO)
        REFERENCES T_CLY_TIPO_ENDERECO(COD_TIPO_ENDERECO),

    CONSTRAINT FK_CLY_END_USUARIO_CIDADE
        FOREIGN KEY (COD_CIDADE)
        REFERENCES T_CLY_CIDADE(COD_CIDADE),

    CONSTRAINT CK_CLY_END_STA_ATIVO
        CHECK (UPPER(STA_ATIVO) IN ('S', 'N'))
);

------------------------------------------------------------
-- TABELA: TELEFONE_USUARIO
------------------------------------------------------------
CREATE TABLE T_CLY_TELEFONE_USUARIO (
    ID_TELEFONE       NUMBER(10)      NOT NULL,
    ID_USUARIO        NUMBER          NOT NULL,
    NUMERO_TELEFONE   VARCHAR2(20)    NOT NULL,

    CONSTRAINT PK_CLY_TELEFONE_USUARIO
        PRIMARY KEY (ID_TELEFONE),

    CONSTRAINT FK_CLY_TEL_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES T_CLY_USUARIO(ID_USUARIO)
);

------------------------------------------------------------
-- TABELA: ESPECIE
------------------------------------------------------------
CREATE TABLE T_CLY_ESPECIE (
    ID_ESPECIE        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME_ESPECIE      VARCHAR2(50)    NOT NULL,

    CONSTRAINT PK_CLY_ESPECIE
        PRIMARY KEY (ID_ESPECIE),

    CONSTRAINT UK_CLY_ESPECIE
        UNIQUE (NOME_ESPECIE)
);

------------------------------------------------------------
-- TABELA: PORTE
------------------------------------------------------------
CREATE TABLE T_CLY_PORTE (
    ID_PORTE          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DESCRICAO         VARCHAR2(30)    NOT NULL,

    CONSTRAINT PK_CLY_PORTE
        PRIMARY KEY (ID_PORTE),

    CONSTRAINT UK_CLY_PORTE
        UNIQUE (DESCRICAO)
);

------------------------------------------------------------
-- TABELA: RACA
------------------------------------------------------------
CREATE TABLE T_CLY_RACA (
    ID_RACA           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_ESPECIE        NUMBER          NOT NULL,
    NOME_RACA         VARCHAR2(100)   NOT NULL,

    CONSTRAINT PK_CLY_RACA
        PRIMARY KEY (ID_RACA),

    CONSTRAINT FK_CLY_RACA_ESPECIE
        FOREIGN KEY (ID_ESPECIE)
        REFERENCES T_CLY_ESPECIE(ID_ESPECIE)
);

------------------------------------------------------------
-- TABELA: PET
------------------------------------------------------------
CREATE TABLE T_CLY_PET (
    ID_PET            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_USUARIO        NUMBER          NOT NULL,
    ID_ESPECIE        NUMBER          NOT NULL,
    ID_RACA           NUMBER          NOT NULL,
    ID_PORTE          NUMBER          NOT NULL,
    NOME              VARCHAR2(100)   NOT NULL,
    DT_NASCIMENTO     DATE,
    PESO              NUMBER(6,2),
    SEXO              CHAR(1)         NOT NULL,
    CASTRADO          CHAR(1)         DEFAULT 'N' NOT NULL,
    DT_CADASTRO       DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_CLY_PET
        PRIMARY KEY (ID_PET),

    CONSTRAINT FK_CLY_PET_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES T_CLY_USUARIO(ID_USUARIO),

    CONSTRAINT FK_CLY_PET_ESPECIE
        FOREIGN KEY (ID_ESPECIE)
        REFERENCES T_CLY_ESPECIE(ID_ESPECIE),

    CONSTRAINT FK_CLY_PET_RACA
        FOREIGN KEY (ID_RACA)
        REFERENCES T_CLY_RACA(ID_RACA),

    CONSTRAINT FK_CLY_PET_PORTE
        FOREIGN KEY (ID_PORTE)
        REFERENCES T_CLY_PORTE(ID_PORTE),

    CONSTRAINT CK_CLY_PET_SEXO
        CHECK (UPPER(SEXO) IN ('M', 'F')),

    CONSTRAINT CK_CLY_PET_CASTRADO
        CHECK (UPPER(CASTRADO) IN ('S', 'N')),

    CONSTRAINT CK_CLY_PET_PESO
        CHECK (PESO IS NULL OR PESO > 0)
);

------------------------------------------------------------
-- TABELA: DISPOSITIVO IOT
------------------------------------------------------------
CREATE TABLE T_CLY_DISPOSITIVO_IOT (
    ID_DISPOSITIVO            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_PET                    NUMBER        NOT NULL,
    DT_ATIVACAO               DATE DEFAULT SYSDATE NOT NULL,
    INTERVALO_COLETA_MIN      NUMBER(5),
    FREQUENCIA_CARDIACA       NUMBER(5),
    NIVEL_ATIVIDADE           NUMBER(5,2),
    PRESSAO                   NUMBER(6,2),
    DT_ULTIMA_LEITURA         DATE,
    STATUS                    VARCHAR2(20)  DEFAULT 'ATIVO' NOT NULL,

    CONSTRAINT PK_CLY_DISPOSITIVO_IOT
        PRIMARY KEY (ID_DISPOSITIVO),

    CONSTRAINT FK_CLY_DISP_PET
        FOREIGN KEY (ID_PET)
        REFERENCES T_CLY_PET(ID_PET),

    CONSTRAINT UK_CLY_DISPOSITIVO_PET
        UNIQUE (ID_PET),

    CONSTRAINT CK_CLY_DISP_STATUS
        CHECK (STATUS IN ('ATIVO', 'INATIVO', 'MANUTENCAO')),

    CONSTRAINT CK_CLY_DISP_INTERVALO
        CHECK (INTERVALO_COLETA_MIN IS NULL OR INTERVALO_COLETA_MIN > 0),

    CONSTRAINT CK_CLY_DISP_FC
        CHECK (FREQUENCIA_CARDIACA IS NULL OR FREQUENCIA_CARDIACA > 0),

    CONSTRAINT CK_CLY_DISP_ATIVIDADE
        CHECK (NIVEL_ATIVIDADE IS NULL OR NIVEL_ATIVIDADE >= 0),

    CONSTRAINT CK_CLY_DISP_PRESSAO
        CHECK (PRESSAO IS NULL OR PRESSAO > 0)
);

------------------------------------------------------------
-- TABELA: LEITURA IOT
------------------------------------------------------------
CREATE TABLE T_CLY_LEITURA_IOT (
    ID_LEITURA                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_DISPOSITIVO            NUMBER        NOT NULL,
    DT_LEITURA                DATE          NOT NULL,
    FREQUENCIA_CARDIACA       NUMBER(5),
    NIVEL_ATIVIDADE           NUMBER(5,2),
    PRESSAO                   NUMBER(6,2),

    CONSTRAINT PK_CLY_LEITURA_IOT
        PRIMARY KEY (ID_LEITURA),

    CONSTRAINT FK_CLY_LEITURA_DISP
        FOREIGN KEY (ID_DISPOSITIVO)
        REFERENCES T_CLY_DISPOSITIVO_IOT(ID_DISPOSITIVO)
);

------------------------------------------------------------
-- TABELA: TIPO ALERTA
------------------------------------------------------------
CREATE TABLE T_CLY_TIPO_ALERTA (
    ID_TIPO_ALERTA      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DESCRICAO           VARCHAR2(100)  NOT NULL,

    CONSTRAINT PK_CLY_TIPO_ALERTA
        PRIMARY KEY (ID_TIPO_ALERTA)
);

------------------------------------------------------------
-- TABELA: ALERTA INTELIGENTE
------------------------------------------------------------
CREATE TABLE T_CLY_ALERTA_INTELIGENTE (
    ID_ALERTA           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_PET              NUMBER          NOT NULL,
    ID_TIPO_ALERTA      NUMBER          NOT NULL,
    NIVEL_RISCO         VARCHAR2(20),
    ORIGEM_ALERTA       VARCHAR2(50),
    MENSAGEM            VARCHAR2(500),
    RECOMENDACAO        VARCHAR2(1000),
    DT_GERACAO          DATE DEFAULT SYSDATE NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'ABERTO' NOT NULL,

    CONSTRAINT PK_CLY_ALERTA
        PRIMARY KEY (ID_ALERTA),

    CONSTRAINT FK_CLY_ALERTA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES T_CLY_PET(ID_PET),

    CONSTRAINT FK_CLY_ALERTA_TIPO
        FOREIGN KEY (ID_TIPO_ALERTA)
        REFERENCES T_CLY_TIPO_ALERTA(ID_TIPO_ALERTA),

    CONSTRAINT CK_CLY_ALERTA_RISCO
        CHECK (NIVEL_RISCO IN ('BAIXO', 'MEDIO', 'ALTO')),

    CONSTRAINT CK_CLY_ALERTA_ORIGEM
        CHECK (ORIGEM_ALERTA IN ('HISTORICO_CLINICO', 'DISPOSITIVO_IOT', 'SISTEMA', 'USUARIO')),

    CONSTRAINT CK_CLY_ALERTA_STATUS
        CHECK (STATUS IN ('ABERTO', 'VISUALIZADO', 'RESOLVIDO'))
);

------------------------------------------------------------
-- TABELA: CLINICA
------------------------------------------------------------
CREATE TABLE T_CLY_CLINICA (
    ID_CLINICA          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME_CLINICA        VARCHAR2(150)   NOT NULL,

    CONSTRAINT PK_CLY_CLINICA
        PRIMARY KEY (ID_CLINICA)
);

------------------------------------------------------------
-- TABELA: PROFISSIONAL
------------------------------------------------------------
CREATE TABLE T_CLY_PROFISSIONAL (
    ID_PROFISSIONAL     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_CLINICA          NUMBER,
    NOME_PROFISSIONAL   VARCHAR2(150)   NOT NULL,

    CONSTRAINT PK_CLY_PROFISSIONAL
        PRIMARY KEY (ID_PROFISSIONAL),

    CONSTRAINT FK_CLY_PROF_CLINICA
        FOREIGN KEY (ID_CLINICA)
        REFERENCES T_CLY_CLINICA(ID_CLINICA)
);

------------------------------------------------------------
-- TABELA: HISTORICO CLINICO
------------------------------------------------------------
CREATE TABLE T_CLY_HISTORICO_CLINICO (
    ID_HISTORICO        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_PET              NUMBER          NOT NULL,
    ID_PROFISSIONAL     NUMBER,
    TIPO_REGISTRO       VARCHAR2(50),
    DESCRICAO           VARCHAR2(500),
    DT_REGISTRO         DATE DEFAULT SYSDATE NOT NULL,
    DT_RETORNO          DATE,
    OBSERVACOES         VARCHAR2(1000),

    CONSTRAINT PK_CLY_HISTORICO
        PRIMARY KEY (ID_HISTORICO),

    CONSTRAINT FK_CLY_HIST_PET
        FOREIGN KEY (ID_PET)
        REFERENCES T_CLY_PET(ID_PET),

    CONSTRAINT FK_CLY_HIST_PROF
        FOREIGN KEY (ID_PROFISSIONAL)
        REFERENCES T_CLY_PROFISSIONAL(ID_PROFISSIONAL),

    CONSTRAINT CK_CLY_HISTORICO_TIPO
        CHECK (
            TIPO_REGISTRO IN (
                'VACINA', 'CONSULTA', 'DOENCA',
                'MEDICAMENTO', 'OBSERVACAO', 'EXAME'
            )
        )
);

------------------------------------------------------------
-- TABELA: LOG ERRO
------------------------------------------------------------
CREATE TABLE T_CLY_LOG_ERRO (
    ID_LOG              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME_PROCEDURE      VARCHAR2(100),
    CODIGO_ERRO         NUMBER,
    MENSAGEM_ERRO       VARCHAR2(4000),
    DATA_ERRO           DATE DEFAULT SYSDATE,
    USUARIO_BANCO       VARCHAR2(100),

    CONSTRAINT PK_CLY_LOG_ERRO
        PRIMARY KEY (ID_LOG)
);
