------------------------------------------------------------
-- PROJETO: CLYVO VET - SAÚDE PREDITIVA PET
-- DISCIPLINA: MASTERING RELATIONAL AND NON-RELATIONAL DATABASE
-- OBJETIVO: APAGAR AS TABELAS RELACIONAIS
------------------------------------------------------------

DROP TABLE T_CLY_ALERTA_INTELIGENTE CASCADE CONSTRAINTS;
DROP TABLE T_CLY_DISPOSITIVO_IOT CASCADE CONSTRAINTS;
DROP TABLE T_CLY_HISTORICO_CLINICO CASCADE CONSTRAINTS;
DROP TABLE T_CLY_PET CASCADE CONSTRAINTS;
DROP TABLE T_CLY_USUARIO CASCADE CONSTRAINTS;