------------------------------------------------------------
-- PROJETO: CLYVO VET - SAÚDE PREDITIVA PET
-- DISCIPLINA: MASTERING RELATIONAL AND NON-RELATIONAL DATABASE
-- OBJETIVO: CRIAÇÃO DAS TABELAS RELACIONAIS
------------------------------------------------------------


------------------------------------------------------------
-- TABELA: T_CLY_USUARIO
-- DESCRIÇÃO: Armazena os dados do tutor/responsável pelo pet.
------------------------------------------------------------
CREATE TABLE T_CLY_USUARIO (
    id_usuario   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(150) NOT NULL,
    cpf          VARCHAR2(14) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    senha        VARCHAR2(255) NOT NULL,
    telefone     VARCHAR2(20),
    endereco     VARCHAR2(255),
    dt_cadastro  DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_cly_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_cly_usuario_cpf UNIQUE (cpf),
    CONSTRAINT uk_cly_usuario_email UNIQUE (email)
);



------------------------------------------------------------
-- TABELA: T_CLY_PET
-- DESCRIÇÃO: Armazena os dados principais do pet.
------------------------------------------------------------

CREATE TABLE T_CLY_PET (
    id_pet          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      NUMBER NOT NULL,
    nome            VARCHAR2(100) NOT NULL,
    especie         VARCHAR2(50) NOT NULL,
    raca            VARCHAR2(100),
    dt_nascimento   DATE,
    peso            NUMBER(6,2),
    sexo            VARCHAR2(20),
    castrado        CHAR(1) DEFAULT 'N' NOT NULL,
    porte           VARCHAR2(20),
    dt_cadastro     DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_cly_pet PRIMARY KEY (id_pet),
    CONSTRAINT fk_cly_pet_usuario FOREIGN KEY (id_usuario)
        REFERENCES T_CLY_USUARIO (id_usuario),

    CONSTRAINT ck_cly_pet_castrado CHECK (castrado IN ('S', 'N')),
    CONSTRAINT ck_cly_pet_sexo CHECK (sexo IN ('MACHO', 'FEMEA', 'NAO_INFORMADO')),
    CONSTRAINT ck_cly_pet_porte CHECK (porte IN ('PEQUENO', 'MEDIO', 'GRANDE', 'NAO_INFORMADO')),
    CONSTRAINT ck_cly_pet_peso CHECK (peso IS NULL OR peso > 0)
);


------------------------------------------------------------
-- TABELA: T_CLY_HISTORICO_CLINICO
-- DESCRIÇÃO: Registra eventos clínicos do pet, como vacinas,
-- consultas, doenças, medicamentos, observações e exames.
------------------------------------------------------------

CREATE TABLE T_CLY_HISTORICO_CLINICO (
    id_historico         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet               NUMBER NOT NULL,
    tipo_registro        VARCHAR2(30) NOT NULL,
    descricao            VARCHAR2(500) NOT NULL,
    dt_registro          DATE DEFAULT SYSDATE NOT NULL,
    dt_retorno           DATE,
    profissional_clinica VARCHAR2(150),
    observacoes          VARCHAR2(1000),

    CONSTRAINT pk_cly_historico_clinico PRIMARY KEY (id_historico),
    CONSTRAINT fk_cly_historico_pet FOREIGN KEY (id_pet)
        REFERENCES T_CLY_PET (id_pet),

    CONSTRAINT ck_cly_historico_tipo CHECK (
        tipo_registro IN (
            'VACINA',
            'CONSULTA',
            'DOENCA',
            'MEDICAMENTO',
            'OBSERVACAO',
            'EXAME'
        )
    )
);


------------------------------------------------------------
-- TABELA: T_CLY_DISPOSITIVO_IOT
-- DESCRIÇÃO: Armazena o dispositivo IoT vinculado ao pet.
-- Para simplificação do MVP, esta tabela também guarda
-- a leitura atual/consolidada mais recente do dispositivo.
------------------------------------------------------------

CREATE TABLE T_CLY_DISPOSITIVO_IOT (
    id_dispositivo            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet                    NUMBER NOT NULL,
    dt_vinculacao             DATE DEFAULT SYSDATE NOT NULL,
    intervalo_coleta_minutos  NUMBER(5),
    frequencia_cardiaca       NUMBER(5),
    nivel_atividade           NUMBER(5,2),
    pressao                   NUMBER(6,2),
    dt_ultima_leitura         DATE,
    status                    VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,

    CONSTRAINT pk_cly_dispositivo_iot PRIMARY KEY (id_dispositivo),
    CONSTRAINT fk_cly_dispositivo_pet FOREIGN KEY (id_pet)
        REFERENCES T_CLY_PET (id_pet),

    CONSTRAINT uk_cly_dispositivo_pet UNIQUE (id_pet),
    CONSTRAINT ck_cly_dispositivo_status CHECK (status IN ('ATIVO', 'INATIVO', 'MANUTENCAO')),
    CONSTRAINT ck_cly_dispositivo_intervalo CHECK (intervalo_coleta_minutos IS NULL OR intervalo_coleta_minutos > 0),
    CONSTRAINT ck_cly_dispositivo_fc CHECK (frequencia_cardiaca IS NULL OR frequencia_cardiaca > 0),
    CONSTRAINT ck_cly_dispositivo_atividade CHECK (nivel_atividade IS NULL OR nivel_atividade >= 0),
    CONSTRAINT ck_cly_dispositivo_pressao CHECK (pressao IS NULL OR pressao > 0)
);



------------------------------------------------------------
-- TABELA: T_CLY_ALERTA_INTELIGENTE
-- DESCRIÇÃO: Armazena os alertas gerados pelo sistema
-- com base no histórico clínico, dados do dispositivo ou regras.
------------------------------------------------------------

CREATE TABLE T_CLY_ALERTA_INTELIGENTE (
    id_alerta      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet         NUMBER NOT NULL,
    tipo_alerta    VARCHAR2(40) NOT NULL,
    nivel_risco    VARCHAR2(20) NOT NULL,
    origem_alerta  VARCHAR2(30) NOT NULL,
    mensagem       VARCHAR2(500) NOT NULL,
    recomendacao   VARCHAR2(1000),
    dt_geracao     DATE DEFAULT SYSDATE NOT NULL,
    status         VARCHAR2(20) DEFAULT 'ABERTO' NOT NULL,

    CONSTRAINT pk_cly_alerta_inteligente PRIMARY KEY (id_alerta),
    CONSTRAINT fk_cly_alerta_pet FOREIGN KEY (id_pet)
        REFERENCES T_CLY_PET (id_pet),

    CONSTRAINT ck_cly_alerta_tipo CHECK (
        tipo_alerta IN (
            'AGUA',
            'ALIMENTACAO',
            'ATIVIDADE',
            'VACINA',
            'MEDICAMENTO',
            'CHECK_UP',
            'COMPORTAMENTO',
            'FREQUENCIA_CARDIACA',
            'PRESSAO'
        )
    ),

    CONSTRAINT ck_cly_alerta_risco CHECK (nivel_risco IN ('BAIXO', 'MEDIO', 'ALTO')),
    CONSTRAINT ck_cly_alerta_origem CHECK (origem_alerta IN ('HISTORICO_CLINICO', 'DISPOSITIVO_IOT', 'SISTEMA', 'USUARIO')),
    CONSTRAINT ck_cly_alerta_status CHECK (status IN ('ABERTO', 'VISUALIZADO', 'RESOLVIDO'))
);