------------------------------------------------------------
-- PROJETO: CLYVO VET - SA�DE PREDITIVA PET
-- DISCIPLINA: MASTERING RELATIONAL AND NON-RELATIONAL DATABASE
-- OBJETIVO: CRIA��O DAS TABELAS RELACIONAIS
------------------------------------------------------------


------------------------------------------------------------
-- TABELA: T_CLY_USUARIO
-- DESCRI��O: Armazena os dados do tutor/respons�vel pelo pet.
------------------------------------------------------------
CREATE TABLE T_CLY_USUARIO (
    id_usuario   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(150) NOT NULL,
    cpf          VARCHAR2(14) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    senha        VARCHAR2(255) NOT NULL,
    telefone     VARCHAR2(20),
    endereco     VARCHAR2(255),
    dt_cadastro  DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_cly_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_cly_usuario_cpf UNIQUE (cpf),
    CONSTRAINT uk_cly_usuario_email UNIQUE (email)
);



------------------------------------------------------------
-- TABELA: T_CLY_PET
-- DESCRI��O: Armazena os dados principais do pet.
------------------------------------------------------------

CREATE TABLE T_CLY_PET (
    id_pet          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      NUMBER NOT NULL,
    nome            VARCHAR2(100) NOT NULL,
    especie         VARCHAR2(50) NOT NULL,
    raca            VARCHAR2(100),
    dt_nascimento   DATE,
    peso            NUMBER(6,2),
    sexo            VARCHAR2(20),
    castrado        CHAR(1) DEFAULT 'N' NOT NULL,
    porte           VARCHAR2(20),
    dt_cadastro     DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_cly_pet PRIMARY KEY (id_pet),
    CONSTRAINT fk_cly_pet_usuario FOREIGN KEY (id_usuario)
        REFERENCES T_CLY_USUARIO (id_usuario),

    CONSTRAINT ck_cly_pet_castrado CHECK (castrado IN ('S', 'N')),
    CONSTRAINT ck_cly_pet_sexo CHECK (sexo IN ('MACHO', 'FEMEA', 'NAO_INFORMADO')),
    CONSTRAINT ck_cly_pet_porte CHECK (porte IN ('PEQUENO', 'MEDIO', 'GRANDE', 'NAO_INFORMADO')),
    CONSTRAINT ck_cly_pet_peso CHECK (peso IS NULL OR peso > 0)
);


------------------------------------------------------------
-- TABELA: T_CLY_HISTORICO_CLINICO
-- DESCRI��O: Registra eventos cl�nicos do pet, como vacinas,
-- consultas, doen�as, medicamentos, observa��es e exames.
------------------------------------------------------------

CREATE TABLE T_CLY_HISTORICO_CLINICO (
    id_historico         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet               NUMBER NOT NULL,
    tipo_registro        VARCHAR2(30) NOT NULL,
    descricao            VARCHAR2(500) NOT NULL,
    dt_registro          DATE DEFAULT SYSDATE NOT NULL,
    dt_retorno           DATE,
    profissional_clinica VARCHAR2(150),
    observacoes          VARCHAR2(1000),

    CONSTRAINT pk_cly_historico_clinico PRIMARY KEY (id_historico),
    CONSTRAINT fk_cly_historico_pet FOREIGN KEY (id_pet)
        REFERENCES T_CLY_PET (id_pet),

    CONSTRAINT ck_cly_historico_tipo CHECK (
        tipo_registro IN (
            'VACINA',
            'CONSULTA',
            'DOENCA',
            'MEDICAMENTO',
            'OBSERVACAO',
            'EXAME'
        )
    )
);


------------------------------------------------------------
-- TABELA: T_CLY_DISPOSITIVO_IOT
-- DESCRI��O: Armazena o dispositivo IoT vinculado ao pet.
-- Para simplifica��o do MVP, esta tabela tamb�m guarda
-- a leitura atual/consolidada mais recente do dispositivo.
------------------------------------------------------------

CREATE TABLE T_CLY_DISPOSITIVO_IOT (
    id_dispositivo            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet                    NUMBER NOT NULL,
    dt_vinculacao             DATE DEFAULT SYSDATE NOT NULL,
    intervalo_coleta_minutos  NUMBER(5),
    frequencia_cardiaca       NUMBER(5),
    nivel_atividade           NUMBER(5,2),
    pressao                   NUMBER(6,2),
    dt_ultima_leitura         DATE,
    status                    VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,

    CONSTRAINT pk_cly_dispositivo_iot PRIMARY KEY (id_dispositivo),
    CONSTRAINT fk_cly_dispositivo_pet FOREIGN KEY (id_pet)
        REFERENCES T_CLY_PET (id_pet),

    CONSTRAINT uk_cly_dispositivo_pet UNIQUE (id_pet),
    CONSTRAINT ck_cly_dispositivo_status CHECK (status IN ('ATIVO', 'INATIVO', 'MANUTENCAO')),
    CONSTRAINT ck_cly_dispositivo_intervalo CHECK (intervalo_coleta_minutos IS NULL OR intervalo_coleta_minutos > 0),
    CONSTRAINT ck_cly_dispositivo_fc CHECK (frequencia_cardiaca IS NULL OR frequencia_cardiaca > 0),
    CONSTRAINT ck_cly_dispositivo_atividade CHECK (nivel_atividade IS NULL OR nivel_atividade >= 0),
    CONSTRAINT ck_cly_dispositivo_pressao CHECK (pressao IS NULL OR pressao > 0)
);



------------------------------------------------------------
-- TABELA: T_CLY_ALERTA_INTELIGENTE
-- DESCRI��O: Armazena os alertas gerados pelo sistema
-- com base no hist�rico cl�nico, dados do dispositivo ou regras.
------------------------------------------------------------

CREATE TABLE T_CLY_ALERTA_INTELIGENTE (
    id_alerta      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pet         NUMBER NOT NULL,
    tipo_alerta    VARCHAR2(40) NOT NULL,
    nivel_risco    VARCHAR2(20) NOT NULL,
    origem_alerta  VARCHAR2(30) NOT NULL,
    mensagem       VARCHAR2(500) NOT NULL,
    recomendacao   VARCHAR2(1000),
    dt_geracao     DATE DEFAULT SYSDATE NOT NULL,
    status         VARCHAR2(20) DEFAULT 'ABERTO' NOT NULL,

    CONSTRAINT pk_cly_alerta_inteligente PRIMARY KEY (id_alerta),
    CONSTRAINT fk_cly_alerta_pet FOREIGN KEY (id_pet)
        REFERENCES T_CLY_PET (id_pet),

    CONSTRAINT ck_cly_alerta_tipo CHECK (
        tipo_alerta IN (
            'AGUA',
            'ALIMENTACAO',
            'ATIVIDADE',
            'VACINA',
            'MEDICAMENTO',
            'CHECK_UP',
            'COMPORTAMENTO',
            'FREQUENCIA_CARDIACA',
            'PRESSAO'
        )
    ),

    CONSTRAINT ck_cly_alerta_risco CHECK (nivel_risco IN ('BAIXO', 'MEDIO', 'ALTO')),
    CONSTRAINT ck_cly_alerta_origem CHECK (origem_alerta IN ('HISTORICO_CLINICO', 'DISPOSITIVO_IOT', 'SISTEMA', 'USUARIO')),
    CONSTRAINT ck_cly_alerta_status CHECK (status IN ('ABERTO', 'VISUALIZADO', 'RESOLVIDO'))
);

-- TABELA: T_CLY_LOG_ERRO

CREATE TABLE T_CLY_LOG_ERRO (
    id_log            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome_procedure    VARCHAR2(100),
    mensagem_erro     VARCHAR2(4000),
    data_erro         DATE DEFAULT SYSDATE,
    usuario_banco     VARCHAR2(100)
);

-- PROCEDURE: T_CLY_USUARIO

CREATE OR REPLACE PROCEDURE PRC_CARGA_USUARIO (
    p_nome        IN VARCHAR2,
    p_cpf         IN VARCHAR2,
    p_email       IN VARCHAR2,
    p_senha       IN VARCHAR2,
    p_telefone    IN VARCHAR2,
    p_endereco    IN VARCHAR2
)
IS

    v_erro VARCHAR2(4000);

BEGIN

    IF LENGTH(p_cpf) < 11 THEN
        RAISE_APPLICATION_ERROR(-20001, 'CPF inválido');
    END IF;

    INSERT INTO T_CLY_USUARIO (
        nome,
        cpf,
        email,
        senha,
        telefone,
        endereco
    )
    VALUES (
        p_nome,
        p_cpf,
        p_email,
        p_senha,
        p_telefone,
        p_endereco
    );

    DBMS_OUTPUT.PUT_LINE('Usuário cadastrado com sucesso');

EXCEPTION

    WHEN DUP_VAL_ON_INDEX THEN

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_USUARIO',
            'CPF ou EMAIL já cadastrado',
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro: CPF ou EMAIL já existente');

    WHEN VALUE_ERROR THEN

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_USUARIO',
            'Erro de valor informado',
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro de valor');

    WHEN OTHERS THEN

        v_erro := SQLERRM;

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_USUARIO',
            v_erro,
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro geral: ' || v_erro);

END;
/

-- PROCEDURE: T_CLY_PET

CREATE OR REPLACE PROCEDURE PRC_CARGA_PET (
    p_id_usuario       IN NUMBER,
    p_nome             IN VARCHAR2,
    p_especie          IN VARCHAR2,
    p_raca             IN VARCHAR2,
    p_dt_nascimento    IN DATE,
    p_peso             IN NUMBER,
    p_sexo             IN VARCHAR2,
    p_castrado         IN CHAR,
    p_porte            IN VARCHAR2
)
IS

    v_usuario NUMBER;
    v_erro    VARCHAR2(4000);

BEGIN

    SELECT COUNT(*)
    INTO v_usuario
    FROM T_CLY_USUARIO
    WHERE id_usuario = p_id_usuario;

    IF v_usuario = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Usuário não encontrado');
    END IF;

    INSERT INTO T_CLY_PET (
        id_usuario,
        nome,
        especie,
        raca,
        dt_nascimento,
        peso,
        sexo,
        castrado,
        porte
    )
    VALUES (
        p_id_usuario,
        p_nome,
        p_especie,
        p_raca,
        p_dt_nascimento,
        p_peso,
        p_sexo,
        p_castrado,
        p_porte
    );

    DBMS_OUTPUT.PUT_LINE('Pet cadastrado com sucesso');

EXCEPTION

    WHEN VALUE_ERROR THEN

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_PET',
            'Erro de valor informado',
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro de valor');

    WHEN OTHERS THEN

        v_erro := SQLERRM;

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_PET',
            v_erro,
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro geral: ' || v_erro);

END;
/

-- PROCEDURE: T_CLY_HISTORICO_CLINICO

CREATE OR REPLACE PROCEDURE PRC_CARGA_HISTORICO (
    p_id_pet               IN NUMBER,
    p_tipo_registro        IN VARCHAR2,
    p_descricao            IN VARCHAR2,
    p_dt_retorno           IN DATE,
    p_profissional         IN VARCHAR2,
    p_observacoes          IN VARCHAR2
)
IS

    v_erro VARCHAR2(4000);

BEGIN

    INSERT INTO T_CLY_HISTORICO_CLINICO (
        id_pet,
        tipo_registro,
        descricao,
        dt_retorno,
        profissional_clinica,
        observacoes
    )
    VALUES (
        p_id_pet,
        p_tipo_registro,
        p_descricao,
        p_dt_retorno,
        p_profissional,
        p_observacoes
    );

    DBMS_OUTPUT.PUT_LINE('Histórico inserido com sucesso');

EXCEPTION

    WHEN VALUE_ERROR THEN

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_HISTORICO',
            'Erro de valor informado',
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro de valor');

    WHEN OTHERS THEN

        v_erro := SQLERRM;

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_HISTORICO',
            v_erro,
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro geral: ' || v_erro);

END;
/

-- PROCEDURE: T_CLY_DISPOSITIVO_IOT

CREATE OR REPLACE PROCEDURE PRC_CARGA_DISPOSITIVO (
    p_id_pet              IN NUMBER,
    p_intervalo           IN NUMBER,
    p_frequencia          IN NUMBER,
    p_nivel_atividade     IN NUMBER,
    p_pressao             IN NUMBER,
    p_status              IN VARCHAR2
)
IS

    v_erro VARCHAR2(4000);

BEGIN

    INSERT INTO T_CLY_DISPOSITIVO_IOT (
        id_pet,
        intervalo_coleta_minutos,
        frequencia_cardiaca,
        nivel_atividade,
        pressao,
        dt_ultima_leitura,
        status
    )
    VALUES (
        p_id_pet,
        p_intervalo,
        p_frequencia,
        p_nivel_atividade,
        p_pressao,
        SYSDATE,
        p_status
    );

    DBMS_OUTPUT.PUT_LINE('Dispositivo cadastrado com sucesso');

EXCEPTION

    WHEN DUP_VAL_ON_INDEX THEN

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_DISPOSITIVO',
            'Pet já possui dispositivo cadastrado',
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Dispositivo duplicado');

    WHEN OTHERS THEN

        v_erro := SQLERRM;

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_DISPOSITIVO',
            v_erro,
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro geral: ' || v_erro);

END;
/

-- PROCEDURE: T_CLY_ALERTA_INTELIGENTE

CREATE OR REPLACE PROCEDURE PRC_CARGA_ALERTA (
    p_id_pet           IN NUMBER,
    p_tipo_alerta      IN VARCHAR2,
    p_nivel_risco      IN VARCHAR2,
    p_origem_alerta    IN VARCHAR2,
    p_mensagem         IN VARCHAR2,
    p_recomendacao     IN VARCHAR2,
    p_status           IN VARCHAR2
)
IS

    v_erro VARCHAR2(4000);

BEGIN

    INSERT INTO T_CLY_ALERTA_INTELIGENTE (
        id_pet,
        tipo_alerta,
        nivel_risco,
        origem_alerta,
        mensagem,
        recomendacao,
        status
    )
    VALUES (
        p_id_pet,
        p_tipo_alerta,
        p_nivel_risco,
        p_origem_alerta,
        p_mensagem,
        p_recomendacao,
        p_status
    );

    DBMS_OUTPUT.PUT_LINE('Alerta cadastrado com sucesso');

EXCEPTION

    WHEN VALUE_ERROR THEN

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_ALERTA',
            'Erro de valor informado',
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro de valor');

    WHEN OTHERS THEN

        v_erro := SQLERRM;

        INSERT INTO T_CLY_LOG_ERRO (
            nome_procedure,
            mensagem_erro,
            usuario_banco
        )
        VALUES (
            'PRC_CARGA_ALERTA',
            v_erro,
            USER
        );

        DBMS_OUTPUT.PUT_LINE('Erro geral: ' || v_erro);

END;
/

-- BLOCO ANONIMO DE CADASTRO DE USUARIO:

BEGIN

    PRC_CARGA_USUARIO(
        'Armando Souza',
        '12345678900',
        'armando@email.com',
        '123456',
        '11999999999',
        'São Paulo'
    );

END;
/

-- BLOCO ANONIMO DE CADASTRO DE PET:

BEGIN

    PRC_CARGA_PET(
        1,
        'Rex',
        'CACHORRO',
        'Golden Retriever',
        TO_DATE('10/05/2021','DD/MM/YYYY'),
        25,
        'MACHO',
        'S',
        'GRANDE'
    );

END;
/

------------------------------------------------------------
-- BLOCO ANTERIOR / ATUAL / PROXIMO
------------------------------------------------------------

DECLARE

    CURSOR c_pet IS
        SELECT id_pet, nome
        FROM T_CLY_PET
        ORDER BY id_pet;

    v_anterior VARCHAR2(100);
    v_atual    VARCHAR2(100);
    v_proximo  VARCHAR2(100);

BEGIN

    OPEN c_pet;

    FETCH c_pet INTO v_anterior, v_atual;

    LOOP

        FETCH c_pet INTO v_proximo, v_atual;

        EXIT WHEN c_pet%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Anterior: ' || v_anterior ||
            ' | Atual: ' || v_atual ||
            ' | Próximo: ' || v_proximo
        );

        v_anterior := v_proximo;

    END LOOP;

    CLOSE c_pet;

END;
/

------------------------------------------------------------
-- RELATÓRIO COM CURSOS EXPLICITO
------------------------------------------------------------

-- USUARIO CADASTRADO:

DECLARE

    CURSOR c_usuarios IS
        SELECT nome, email
        FROM T_CLY_USUARIO;

    v_nome  VARCHAR2(150);
    v_email VARCHAR2(150);

BEGIN

    OPEN c_usuarios;

    LOOP

        FETCH c_usuarios INTO v_nome, v_email;

        EXIT WHEN c_usuarios%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Nome: ' || v_nome ||
            ' | Email: ' || v_email
        );

    END LOOP;

    CLOSE c_usuarios;

END;
/

-- PETS CADASTRADOS

DECLARE

    CURSOR c_pets IS
        SELECT nome, especie, peso
        FROM T_CLY_PET;

    v_nome      VARCHAR2(100);
    v_especie   VARCHAR2(50);
    v_peso      NUMBER;

BEGIN

    OPEN c_pets;

    LOOP

        FETCH c_pets INTO v_nome, v_especie, v_peso;

        EXIT WHEN c_pets%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Pet: ' || v_nome ||
            ' | Espécie: ' || v_especie ||
            ' | Peso: ' || v_peso
        );

    END LOOP;

    CLOSE c_pets;

END;
/

-- HISTÓRICO CLINICO: 

DECLARE

    CURSOR c_historico IS
        SELECT tipo_registro, descricao
        FROM T_CLY_HISTORICO_CLINICO;

    v_tipo        VARCHAR2(30);
    v_descricao   VARCHAR2(500);

BEGIN

    OPEN c_historico;

    LOOP

        FETCH c_historico INTO v_tipo, v_descricao;

        EXIT WHEN c_historico%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Tipo: ' || v_tipo ||
            ' | Descrição: ' || v_descricao
        );

    END LOOP;

    CLOSE c_historico;

END;
/

-- ALERTAS INTELIGENTES:
DECLARE

    CURSOR c_alerta IS
        SELECT tipo_alerta, nivel_risco, status
        FROM T_CLY_ALERTA_INTELIGENTE;

    v_tipo     VARCHAR2(40);
    v_risco    VARCHAR2(20);
    v_status   VARCHAR2(20);

BEGIN

    OPEN c_alerta;

    LOOP

        FETCH c_alerta INTO v_tipo, v_risco, v_status;

        EXIT WHEN c_alerta%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Alerta: ' || v_tipo ||
            ' | Risco: ' || v_risco ||
            ' | Status: ' || v_status
        );

    END LOOP;

    CLOSE c_alerta;

END;
/